#!/usr/local/bin/node

if (process.argv.length < 3) {
  console.log("please provide a url as a parameter");
  process.exit(0);
}

const axios = require('axios');
let url = process.argv[2];
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

axios.get(url).then(function (response) {
  let body = response.data.toString();
  // Simulate a Document Object Model.
  let { document } = (new JSDOM(body)).window;

  let paragraphs = document.querySelectorAll("p");
  let references = document.querySelectorAll(".reference");

  references.forEach(function (reference) {
    reference.remove();
  });

  paragraphs.forEach(function (paragraph) {
    console.log(paragraph.textContent);
  });
});


